countries = set([
  "Afghanistan"
, "Albania"
, "Algeria"
, "Andorra"
, "Angola"
, "Antigua and Barbuda"
, "Argentina"
, "Armenia"
, "Australia"
, "Austria"
, "Azerbaijan"
, "The Bahamas" , "Bahamas"
, "Bahrain"
, "Bangladesh"
, "Barbados"
, "Belarus"
, "Belgium"
, "Belize"
, "Benin"
, "Bermuda"
, "Bhutan"
, "Bolivia"
, "Bosnia and Herzegovina"
, "Botswana"
, "Brazil"
, "British Virgin Islands"
, "Brunei"
, "Bulgaria"
, "Burkina Faso"
, "Burundi"
, "Cambodia"
, "Cameroon"
, "Canada"
, "Cape Verde"
, "Cayman Islands"
, "Central African Republic"
, "Chad"
, "Chile"
, "China"
, "Colombia"
, "Comoros"
, "Republic of the Congo"
, "Democratic Republic of the Congo"
, "Costa Rica"
, "Cote d'Ivoire"
, "Croatia"
, "Cuba"
, "Cyprus"
, "Czech Republic"
, "Denmark"
, "Djibouti"
, "Dominica"
, "Dominican Republic"
, "East Timor (Timor-Leste)"
, "Ecuador"
, "Egypt"
, "El Salvador"
, "Equatorial Guinea"
, "Eritrea"
, "Estonia"
, "Ethiopia"
, "Falkland Islands"
, "Fiji"
, "Finland"
, "France"
, "Gabon"
, "The Gambia"
, "Georgia"
, "Germany"
, "Ghana"
, "Gibraltar"
, "Greece"
, "Grenada"
, "Guatemala"
, "Guernsey"
, "Guinea"
, "Guinea-Bissau"
, "Guyana"
, "Haiti"
, "Honduras"
, "Hong Kong"
, "Hungary"
, "Iceland"
, "India"
, "Indonesia"
, "Iran"
, "Iraq"
, "Ireland"
, "Isle of Man"
, "Israel"
, "Italy"
, "Jamaica"
, "Japan"
, "Jersey"
, "Jordan"
, "Kazakhstan"
, "Kenya"
, "Kiribati"
, "North Korea"
, "South Korea"
, "Korea"
, "Kosovo"
, "Kuwait"
, "Kyrgyzstan"
, "Laos"
, "Latvia"
, "Lebanon"
, "Lesotho"
, "Liberia"
, "Libya"
, "Liechtenstein"
, "Lithuania"
, "Luxembourg"
, "Macau"
, "Macedonia"
, "Madagascar"
, "Malawi"
, "Malaysia"
, "Maldives"
, "Mali"
, "Malta"
, "Marshall Islands"
, "Mauritania"
, "Mauritius"
, "Mexico"
, "Federated States of Micronesia"
, "Moldova"
, "Monaco"
, "Mongolia"
, "Montenegro"
, "Morocco"
, "Mozambique"
, "Myanmar", "Burma"
, "Namibia"
, "Nauru"
, "Nepal"
, "Netherlands"
, "New Zealand"
, "Nicaragua"
, "Niger"
, "Nigeria"
, "Norway"
, "Oman"
, "Pakistan"
, "Palau"
, "Panama"
, "Papua New Guinea"
, "Paraguay"
, "Peru"
, "Philippines"
, "Poland"
, "Portugal"
, "Qatar"
, "Romania"
, "Russia"
, "Rwanda"
, "Saint Kitts and Nevis"
, "Saint Lucia"
, "Saint Vincent and the Grenadines"
, "Samoa"
, "San Marino"
, "Sao Tome and Principe"
, "Saudi Arabia"
, "Senegal"
, "Serbia"
, "Seychelles"
, "Sierra Leone"
, "Singapore"
, "Slovakia"
, "Slovenia"
, "Solomon Islands"
, "Somalia"
, "South Africa"
, "South Sudan"
, "Spain"
, "Sri Lanka"
, "Sudan"
, "Suriname"
, "Swaziland"
, "Sweden"
, "Switzerland"
, "Syria"
, "Taiwan"
, "Tajikistan"
, "Tanzania"
, "Thailand"
, "Togo"
, "Tonga"
, "Trinidad and Tobago"
, "Tunisia"
, "Turkey"
, "Turkmenistan"
, "Tuvalu"
, "Uganda"
, "Ukraine"
, "United Arab Emirates", "UAE"
, "United Kingdom", "UK"
, "United States of America", "USA"
, "United States"
, "Uruguay"
, "Uzbekistan"
, "Vanuatu"
, "Vatican City (Holy See)"
, "Venezuela"
, "Vietnam"
, "Yemen"
, "Zambia"
, "Zimbabwe"
])